
services:
  postgres:
    container_name: riki
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6969:5432"

volumes:
  postgres_data:

