// config.ts
export const ENV_VARS = {
    RIKI_API_BASE_URL: "RIKI_API_BASE_URL",
    MAIN_DB_HOST: "MAIN_DB_HOST",
    MAIN_DB_PORT: "MAIN_DB_PORT",
    MAIN_DB_USER: "MAIN_DB_USER",
    MAIN_DB_PASS: "MAIN_DB_PASS",
    MAIN_DB_NAME: "MAIN_DB_NAME",
    APP_DB_NAME: "APP_DB_NAME",
    PORT: "PORT",
  };
  